### ISSUE TITLE
Remote Ollama server

### ISSUE THREAD

**Issue by Tycho-S** [h1ddenpr0cess20/ollamarama-matrix#15]
It would be really great if this could talk to a remote ollama server through its API :)

**Comment by h1ddenpr0cess20** [comment]
i'll have to look into how to do that with this version, but i have a similar program [infinigpt-matrix](https://github.com/h1ddenpr0cess20/infinigpt-matrix) which lets you use the ollama api server, and you should be able to just swap in the remote url where the localhost url is.  this is speculation since i haven't gotten around to testing a remote ollama server yet.  let me know if it works for you.

**Comment by Tycho-S** [comment]
Oh thanks!! I'll try that out!

**Comment by h1ddenpr0cess20** [comment]
now that i've looked over my code again, you can probably just do the same thing on this version.  didn't think of it earlier.  should just be able to replace the localhost with your remote server
```
 #generate Ollama model response
    async def respond(self, channel, sender, message, sender2=None):
        try:
            #Generate response
            response = completion(
                api_base="http://localhost:11434",
                model=self.model,
                temperature=self.temperature,
                top_p=self.top_p,
                repeat_penalty=self.repeat_penalty,
                messages=message,
                timeout=60
                ) 
```

**Comment by h1ddenpr0cess20** [comment]
just pushed an update to move the api url into config,json to make it easier
